---
resources:
- name: quotes-service
  type: git
  source:
    uri: https://github.com/kirederik/quotes-service

- name: cf-prod
  type: cf
  source:
    api: {{prod_cf_api}}
    username: {{prod_cf_username}}
    password: {{prod_cf_password}}
    organization: {{prod_cf_org}}
    space: {{prod_cf_space}}
    skip_cert_check: true

jobs:
- name: unit-test
  public: true
  serial: true
  plan:
  - get: quotes-service
    trigger: true
  - task: unit-test-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: '8'
      inputs:
        - name: quotes-service
      run:
        path: sh
        args:
        - -exc
        - |
          cd quotes-service
          ./gradlew test
      params:
        TERM: dumb
        version: 0.4.0

- name: deploy
  public: true
  serial: true
  plan:
  - get: quotes-service
    passed: [unit-test]
    trigger: true
  - task: build-task
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: java
          tag: '8'
      inputs:
        - name: quotes-service
      outputs:
        - name: built-project
      run:
        path: sh
        args:
        - -exc
        - |
          cd quotes-service
          ./gradlew assemble manifestFilter
          cp -arv build/* ../built-project
      params:
        TERM: dumb
        version: 0.4.0
  - put: cf-prod
    params:
      manifest: built-project/manifest.yml
      environment_variables:
        CF_TARGET: {{prod_cf_api}}
