---
jobs:
- name: unit-test
  public: true
  serial: true
  plan:
  - get: quotes-service
    trigger: true

resources:
- name: quotes-service
  type: git
  source:
    uri: https://github.com/kirederik/quotes-service
